# Generated by Django 3.2.9 on 2021-11-15 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('auth_id', models.AutoField(primary_key=True, serialize=False)),
                ('auth_name', models.CharField(max_length=100)),
                ('bio', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
