# Generated by Django 3.2.9 on 2021-11-15 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author_forien_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='author.author'),
        ),
    ]
